spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8888
  kafka:
    bootstrap-servers: kafka:29092
  zipkin:
    base-url: http://zipkins:9411/
  datasource:
    username: sa
    password: sa
    url: jdbc:h2:file:./data/demo;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
feign:
  circuitbreaker:
    enabled: true
resilience4j:
  circuitbreaker:
    instances:
      orderService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED
server:
  port: 9093