spring:
  application:
    name: product-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev
  zipkin:
    base-url: http://zipkins:9411/
server:
  port: 9090