spring:
  data:
    mongodb:
      uri: mongodb://product_service_db:27017/product_service
  redis:
    host: redis
    port: 6379
resilience4j:
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka